### ISSUE TITLE
XmlText Constructor not recognised?

### ISSUE THREAD

**Issue by lubi888** [renggli/dart-xml#19]
Trying to follow the most basic code from the docs and what's wrong with this code that's it's producing error?

```
import 'package:xml/xml.dart' as xml;

void main(){
var bookshelfXml = '''<?xml version="1.0"?>
    <bookshelf>
      <book>
        <title lang="english">Growing a Language</title>
        <price>29.99</price>
      </book>
      <book>
        <title lang="english">Learning XML</title>
        <price>39.95</price>
      </book>
      <price>132.00</price>
    </bookshelf>''';
var document = xml.parse(bookshelfXml);

print(document.toString());
print('-------------------');
var textual = document.descendants
    .where((node) => node is XmlText && !node.text.trim().isEmpty)
    .join('\n');
print(textual);

//the following works fine.
// var titles = document.findAllElements('title');
// titles
//     .map((node) => node.text)
//     .forEach(print);
}

```

the error produced is;

```
Unhandled exception:
'file:///home/xxxxx/dart/xmlXSLT/bookxml.dart': malformed type: line 21 pos 30: type 'XmlText' is not loaded
    .where((node) => node is XmlText && !node.text.trim().isEmpty)
                             ^


#0      _TypeError._throwNew (dart:core-patch/errors_patch.dart:65)
#1      main.<anonymous closure> (file:///home/iveagh/dart/xmlXSLT/bookxml.dart:21:30)
#2      WhereIterator.moveNext (dart:_internal/iterable.dart:439)
#3      Iterable.join (dart:core/iterable.dart:303)
#4      main (file:///home/iveagh/dart/xmlXSLT/bookxml.dart:22:6)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

```

**Comment by renggli** [comment]
Oups, that's a bug in the docs. The package is imported `as xml`, so you need to prefix all references with `xml.`, i.e. `xml.XmlText`. I'll update the docs in a second.

**Comment by lubi888** [comment]
wow that was quick! 
thanks so much, renggli

**Comment by renggli** [comment]
Fixed in 3b3e355d71d83b61d5e38b57dd7303ba05bbd165.

Please let me know if you encounter other problems!

**Comment by lubi888** [comment]
Hi renggli,
no other probs yet but if i wanted to ask you simple questions about Dart, Xml and Xslt and using and Xml database where would be the best place to do that?

would it be stackoverflow, dartlang.slack (or perhaps some other slack) or just gmail||G+ you?

if you don't have time that's ok.....

**Comment by renggli** [comment]
Preferably ask on StackOverflow, I think you can reach the widest community there.

**Comment by lubi888** [comment]
thanks, renggli. later....
